### ISSUE TITLE
ELECTRICAL: Update links to supplier documentation

### ISSUE THREAD

**Issue by WattsUp** [CougsInSpace/CougSat1-Hardware#473]
I refactored the supplier documentation folder and all links to it need to be fixed :)

**Comment by WattsUp** [comment]
- [ ] Avionics part of #494
- [ ] Backplane
- [x] EPS
- [ ] Solar Panel
- [ ] Comms
- [ ] +X Panel
- [ ] -Z Panel part of #471
- [ ] Umbilical part of #472
